### PR TITLE
upload Galaxy tutorial

### PR DESCRIPTION
**Pull request by kcarolin**

### CODE REVIEW

**Comment by kcarolin** [comment]
Issue #6: Tutorial Using Galaxy for RNA-Seq
Uploaded PDF file RNA_seq_Galaxy_KC guide

**Comment by danielanach** [comment]
Hi @kcarolin ,

This is a great tutorial start, I would love a couple of changes though prior to merging:

- [x] Can you make it clear at the top of the file what kind of tutorial this is: i.e., big title or something like that. You can also remove any "I" statements as this is meant to be a generic tutorial for everyone to use. 
- [x] Since galaxy does not require any code, it would be really helpful to include some screenshots into your tutorial in lieu of code. 

Once these changes are implemented then we will be happy to give you the extra credit!

**Comment by kcarolin** [comment]
[RNA_seq_Galaxy_KC.pdf](https://github.com/biom262/biom262-2019/files/3000967/RNA_seq_Galaxy_KC.pdf)

**Comment by kcarolin** [comment]
Provided title, generalized statements, included screenshots

**Comment by danielanach** [comment]
The changes look awesome @kcarolin !! The tutorial is much more clear now. Thank you! Your extra credit is approved.

**Pull request merged**
